from library_management import *
from auth import *

admin = Admin("Sabbir", "sabbir@gmail.com", "sabbir123")
# print(admin)

# m1 = User("Saima", "saima@gmail.com", "saima123")
# # m2 = User("Saimaalam", "saimaalam@gmail.com", "saimaalam123")
# admin.add_book()
# admin.update_book()
# admin.search_book()
# admin.add_book(b1)
# admin.add_book(b2)
# admin.update_book(1001, "Kane")
# admin.delete_book(1001)

# admin.add_book()
# admin.update_book()
# admin.search_book()
# admin.add_book()
# show_books_db()
# print(book_collection)
# admin.add_book()
# show_books_db()
# # admin.delete_book()
# admin.delete_book()
# print(book_collection)
# admin.add_book()
# admin.add_book()
# admin.add_book()
# admin.delete_book()
# show_books_db()
# admin.update_book()
# show_books_db()

# admin.delete_member()
# admin.update_member()
# show_members_db()

# m1 = register()
# print(m1)
m1 = register()
m1.borrow_book()
